# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://zm-traduction.com
title: Zuzana Mahutova
email: your-email@domain.com
author: Zuzana Mahutova
description: > # "Write an awesome description for your new site here. 
  Traducteur indépendant français – slovaque – tchèque
copyright: 'Copyright &copy; 2018 Zuzana Mahutova. All Rights Reserved.'
credits: ''

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

